server:
  port: 13443
  error:
    include-stacktrace: on_param
  ssl:
    protocol: TLS
    enabled-protocols: TLSv1.3
    bundle: "eudi-issuer"

spring:
  application:
    name: eudi-qeaa-issuer-poc
  ssl:
    bundle:
      pem:
        eudi-issuer:
          key:
            alias: eudi-issuer.localhost
          keystore:
            certificate: classpath:eudi-issuer.localhost.crt
            private-key: classpath:eudi-issuer.localhost.key
          truststore:
            certificate: classpath:eudi-ca.localhost.crt
  sql:
    init:
      mode: embedded
      platform: h2
  jpa:
    defer-datasource-initialization: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:eudi-issuer
    username: sa
    password:
  main:
    banner-mode: off
  mvc:
    log-resolved-exception: false

management:
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
  endpoints:
    web:
      exposure:
        include: configprops,env,health,info
  info:
    git:
      mode: full
    java:
      enabled: true
    os:
      enabled: true

eudi:
  issuer:
    #subject-test-data: classpath:subject-data.json
    base-url: https://eudi-issuer.localhost:13443
    max-clock-skew: 5s
    key-proof-expiry-time: 60s
    dpop-expiry-time: 60s
    c-nonce-expiry-time: 7d
    credential:
      encryption:
        required: false
        supported-algorithms:
          - RSA-OAEP
          - RSA-OAEP-256
          - ECDH-ES
          - ECDH-ES+A128KW
          - ECDH-ES+A192KW
          - ECDH-ES+A256KW
        supported-encodings:
          - A128GCM
          - A192GCM
          - A256GCM
          - A128CBC-HS256
          - A192CBC-HS384
          - A256CBC-HS512
      validity: 7d
      max-batch-size: 50
    metadata:
      supported-locales:
        - en
        - et
        - ru
  as:
    base-url: https://eudi-as.localhost:12443
    metadata:
      interval: PT24H
      max-attempts: 1440
      backoff-delay-milliseconds: 1000
      backoff-max-delay-milliseconds: 60000
      backoff-multiplier: 1.1
